pulumi_config_passphrase: ENC[AES256_GCM,data:D+Unq6gmtvsTXM9ZM51EhMapwJ0OXN1mREGQhKfjd+s=,iv:MbPksOUYTx9Aenkz2Uv17DB4LSKAqv5V7odrN0j9iJc=,tag:WSBWqD78QqzCgncV3WPm+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYlFIbFdvY081MFpYU3Bu
            eXVpeUNXT2UyQlFDd3g2SllkaTU4UDFSU0QwCnc3ZmNMamd1VTV6dEpub0wzSGJM
            cmVvbkloalQ3SEpSRUppN2VoL3JIS0EKLS0tIDQ1bURrKzMrY0N4Unl6S0FkcWNt
            VkRGWWlnNVhNL0syVzk2MVBmaGExLzgKEiOTE4Hhc85IFyi8z/AqnGSo30aXfsJf
            Fasz7rngxuQNvb6s8VlxFyIEeKmrvnKSvkOx0gyad9o48iTumiLloQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c8rzq8txxlq4g6zu0yn46rr9rdzfyn3j5u9d8cxnq2h5w3yrve6sjs3gkc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTFZEZ3Ivcm9SQmJvbUJG
            dzV0ZElLRk8wSFAvOUtXcUxodWN4N0hDQUdvCnhnTFNVL2xhM09UdVg3TWovd2Nj
            OUNLTE45enVza3Rhb3pxZlgxaWlCVG8KLS0tIE1LSWk0RllDYld5UkFWamIrNVNK
            YWZBeERmbGtHMnlUak5YQnlhQUhmNUkKquU2oMl5YnaR7d1qcNBorfXLhl9fSg0r
            7ARfoQ5bMcIUiPiaFte/OZkp9pTd2kZ48Ti92WKC+kvn0JhihR0jzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ewkw53p9v6w44uae75kxnnwnmnt9etqpkems2kjqkyjwldrjju0qe2t4tn
    lastmodified: "2026-07-01T04:35:28Z"
    mac: ENC[AES256_GCM,data:z1jRMyWBoWSO628dhh6IQ/ZQaBceoZKryYQHZ0vfOdY6AMfWEvnCFE+DJzbwHXrukncI6Ct7dlysY4ZcsZmd9zW1EGxs3GJPHtJOu/RztE/PDjctGX7qmYWcp9Jc06LDbx99tVTNk8q7IHy9z6oxBXN19mZ++SBg8V5+wYzTKaU=,iv:twhi9+ajHNgBJ1MK6P9rqFhInL3STk4IZG+n4B9QAn0=,tag:Vz/1/8MnstvrKr/SdcUFzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
